### ISSUE TITLE
Problem with tinyply version

### ISSUE THREAD

**Issue by Gatsby23** [razayunus/ManhattanSLAM#1]
Hi, Sorry to trobule you. But what is your tinlyply version? There have a version 2.3 on my laptop, it shows that this error:
```
make[2]: *** No rule to make target '/usr/local/lib/libtinyply.so', needed by '../lib/libManhattanSLAM.so'.  Stop.
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/ManhattanSLAM.dir/all' failed
```

**Comment by yilu-zhang** [comment]
get tinyply from [here](https://github.com/ddiakopoulos/tinyply)
before install tinyply, change the line 17 of CmakeLists.txt:
`set(SHARED_LIB false CACHE BOOL "Build as shared library")` to

`set(SHARED_LIB true CACHE BOOL "Build as shared library")`

then install tinyply
`cd tinyply
mkdir build
cd build
cmake ..
make
sudo make install
sudo cp /usr/local/lib/libtinyply.so /`
